hps/urls.py
from django.contrib import admin
from django.urls import path
from hpsapp import urls as hpsapp_urls
from django.conf.urls import include
from hpsapp.views import *

app_name = 'hpsapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(hpsapp_urls, namespace='hpsapp')),
]

hpsapp/urls.py
from django.urls import path, reverse_lazy
from hpsapp.views import *
from django.contrib.auth.views import LogoutView

app_name = 'hpsapp'

urlpatterns = [
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='hpsapp:login'), name='logout'),
    path('signup/labtechnician/', LabTechnicianSignUpView.as_view(),
         name='labtechnician_signup'),
    path('signup/doctor/', DoctorSignUpView.as_view(), name='doctor_signup'),
    
    path('labtech/dashboard/', LabTechnicianDashboardView.as_view(), name='labtech_dashboard'),
    path('doctor/dashboard/', DoctorDashboardView.as_view(), name='doctor_dashboard'),
    path('nurse/dashboard/', NurseDashboardView.as_view(), name='nurse_dashboard'),
    
    path('receptionist/dashboard/', ReceptionistDashboardView.as_view(), name='receptionist_dashboard'),
    
    # path('receptionist/patient/search/', SearchPatientView.as_view(), name='receptionist_search'),
    # path('receptionist/patient/<int:patient_id>/assign-doctor/', assign_doctor_to_patient, name='assign_doctor'),
    path('receptionist/patient/search/', SearchPatientView.as_view(), name='receptionist_search'),
    path('receptionist/patient/<int:patient_id/assign-doctor/', SearchPatientView.as_view(), name='assign_doctor'),
    
    path('patient/all/', PatientListView.as_view(), name='patient_list'),
    path('receptionist/patient/<int:patient_id>/assign-doctor/', assign_doctor_to_patient, name='assign_doctor_test'),
]

hpsapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission

# Create your models here.
class User(AbstractUser):
    is_doctor = models.BooleanField(default=False)
    is_labtech = models.BooleanField(default=False)
    is_receptionist = models.BooleanField(default=False)
    is_nurse = models.BooleanField(default=False)
    is_patient = models.BooleanField(default=False)
    phone_number = models.CharField(
        max_length=15, verbose_name="Phone Number", null=True)
    
    groups = models.ManyToManyField(Group, blank=True, related_name='custom_user_set', verbose_name=('groups'), help_text=(
        'The groups this user belongs to. A user will get all permissions granted to each of their groups.'),)
    user_permissions = models.ManyToManyField(Permission, blank=True, related_name='custom_user_set', verbose_name=(
        'user permissions'), help_text=('Specific permissions for this user.'),)


class Doctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    specialization = models.CharField(max_length=255, null=True, blank=True)
    
    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = 'Doctor'
        verbose_name_plural = 'Doctors'

class LabTechnician(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = 'Lab Technician'
        verbose_name_plural = 'Lab Technicians'
        
class Receptionist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    
    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = 'Receptionist'
        verbose_name_plural = 'Receptionists'
        
class Nurse(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    
    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Nurse'
        verbose_name_plural = 'Nurses'
        
class Patient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    # doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, null=True, blank=True)
    age = models.IntegerField(null=True, blank=True)
    sex = models.BooleanField(null=True)
    
    def __str__(self):
        return self.user.username
    
    @property
    def gender(self):
        return "Male" if self.sex else "Female"
    
    class Meta:
        verbose_name = 'Patient'
        verbose_name_plural = 'Patients'

class PreConsultationTest(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    height = models.FloatField(null=True, help_text="(cm)")
    weight = models.FloatField(null=True, help_text="(kg)")
    systolic_pressure = models.FloatField(null=True, blank=True, help_text="Systolic blood pressure in mmHg")
    diastolic_pressure = models.FloatField(null=True, blank=True, help_text="Diastolic blood pressure in mmHg")
    recorded_by = models.ForeignKey(Nurse, on_delete=models.CASCADE)
    recorded_at = models.DateTimeField(auto_now_add=True)
    
class DiagnosticTest(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    labtech = models.ForeignKey(LabTechnician, on_delete=models.CASCADE)
    anaemia = models.BooleanField(null=True)
    high_blood_pressure = models.BooleanField(null=True)
    diabetes = models.BooleanField(null=True)
    smoking = models.BooleanField(null=True)
    creatine_phosphokinase = models.FloatField(null=True, help_text="CPK enzyme level (mcg/L)")
    ejection_fraction = models.FloatField(null=True, help_text="Percentage of blood leaving the heart at each contraction (percentage)")
    platelets = models.FloatField(null=True, help_text="(kiloplatelets/mL)")
    serum_creatinine = models.FloatField(null=True, help_text="(mg/dL)")
    serum_sodium = models.FloatField(null=True, help_text="(mEq/L)")
    death_event = models.BooleanField(null=True)
    recorded_at = models.DateTimeField(auto_now_add=True)
    
class PatientAppointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    scheduled_time = models.DateTimeField(auto_now_add=True)
    status_choices = (
        ('R', 'Registred - In pre-consultation'),
        ('P', 'Pre-consultated - In consultation'),
        ('C', 'Consulted - Awaiting Diagnostic test'),
        ('D', 'Diagnostic tested - Awaiting Feedback'),
        ('F', 'Feedback'),
    )
    status = models.CharField(max_length=1, choices=status_choices, default='R')
    # preconsultation_test = models.OneToOneField(PreConsultationTest, on_delete=models.SET_NULL, null=True, blank=True)
    # diagnostic_test = models.OneToOneField(DiagnosticTest, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
        return f"{self.patient.user.username} - {self.doctor.user.username}"

hpsapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import get_user_model
User = get_user_model()


# Sign Up form for Labtech
class LabtechSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields

# Sign Up form for Doctor
class DoctorSignUpForm(UserCreationForm):
    department = forms.CharField(max_length=25)
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('department',)

hpsapp/views.py
from .forms import DoctorSignUpForm, LabtechSignUpForm
from .models import LabTechnician, Doctor, User, Patient, PatientAppointment
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView, View, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from functools import reduce
from django.core.paginator import Paginator
import logging

############################################################################################
#                                   GENERAL VIEWS
############################################################################################
class CustomLoginView(LoginView):
    template_name = 'hpsapp/login.html'

    def form_valid(self, form):
        user = form.get_user()
        if user.is_labtech:
            self.next_page = 'hpsapp:labtech_dashboard'
        elif user.is_doctor:
            self.next_page = 'hpsapp:doctor_dashboard'
        elif user.is_nurse:
            self.next_page = 'hpsapp:nurse_dashboard'
        elif user.is_receptionist:
            self.next_page = 'hpsapp:receptionist_dashboard'
        else:
            self.next_page = 'hpsapp:login'
            
        return super().form_valid(form)

############################################################################################
#                                   MIXINS
############################################################################################
class DoctorRequiredMixin(UserPassesTestMixin):
    raise_exception = True
    permission_denied_message = "Doctor access only"

    def test_func(self):
        return self.request.user.is_doctor
    
class LabtechRequiredMixin(UserPassesTestMixin):
    raise_exception = True
    permission_denied_message = "LabTech access only"

    def test_func(self):
        return self.request.user.is_labtech
    
class NurseRequiredMixin(UserPassesTestMixin):
    raise_exception = True
    permission_denied_message = "Nurse access only"

    def test_func(self):
        return self.request.user.is_nurse

class ReceptionistRequiredMixin(UserPassesTestMixin):
    raise_exception = True
    permission_denied_message = "Receptionist access only"

    def test_func(self):
        return self.request.user.is_receptionist
    
############################################################################################
#                                   LABTECH'S VIEWS
############################################################################################
class LabTechnicianSignUpView(CreateView):
    form_class = LabtechSignUpForm
    template_name = 'hpsapp/signup.html'
    success_url = reverse_lazy('hpsapp:login')

    def form_valid(self, form):
        # Save the user object
        user = form.save(commit=False)
        user.is_labtech = True
        print(user)
        user.save()

        # Create a new LabTechnician object for the user
        labtech = LabTechnician.objects.create(user=user)
        labtech.save()

        return redirect('hpsapp:login')
    
    def form_invalid(self, form):
        # Print the form errors to the console
        print(form.errors)

        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Lab Technician Signup'
        return context
    
class LabTechnicianDashboardView(LoginRequiredMixin, LabtechRequiredMixin, TemplateView):
    template_name = 'hpsapp/labtech_dashboard.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Lab Technician Dashboard'
        return context
    

############################################################################################
#                                   DOCTOR'S VIEWS
############################################################################################
class DoctorSignUpView(CreateView):
    model = User
    form_class = DoctorSignUpForm
    template_name = 'hpsapp/signup.html'
    success_url = reverse_lazy('hpsapp:login')

    def form_valid(self, form):
        # Save the user object
        user = form.save(commit=False)
        user.is_doctor = True
        user = form.save()

        # Create a new Doctor object for the user
        doctor = Doctor.objects.create(user=user, department=form.cleaned_data.get('department'))
        return redirect('hpsapp:login')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Doctors Signup'
        return context
    

class DoctorDashboardView(LoginRequiredMixin, DoctorRequiredMixin, TemplateView):
    template_name = 'hpsapp/doctor_dashboard.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Doctor Dashboard'
        return context
    

############################################################################################
#                                   RECEPTIONIST'S VIEWS
############################################################################################
class ReceptionistDashboardView(LoginRequiredMixin, ReceptionistRequiredMixin, TemplateView):
    template_name = 'hpsapp/receptionist_dashboard.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Receptionist Dashboard'
        return context
    
# correct search view
class SearchPatientView(View):
    def get(self, request):
        query = request.GET.get('q')
        if not query:
            messages.warning(request, 'Please enter a search query')
            return redirect('hpsapp:receptionist_dashboard')
        words = query.split()
        patients = Patient.objects.filter(
            reduce(lambda x, y: x | y, [
                Q(user__username__icontains=word) |
                Q(user__first_name__icontains=word) |
                Q(user__last_name__icontains=word)
                for word in words])
        ).distinct()

        if not patients:
            messages.warning(request, 'No results found for query: {}'.format(query))
            return redirect('hpsapp:receptionist_dashboard')

        doctors = Doctor.objects.all()

        context = {
            'patients': patients,
            'doctors': doctors,
            'title': 'Receptionist Dashboard',
        }
        return render(request, 'hpsapp/receptionist_patient_list.html', context=context)

    def post(self, request):
        patient_id = request.POST.get('patient_id')
        doctor_id = request.POST.get('doctor_id')

        try:
            print("starting the function patient")
            patient = get_object_or_404(Patient, user_id=int(patient_id))
            print("Finished the fnction patient")
            doctor = get_object_or_404(Doctor, user_id=int(doctor_id))  
            appointment = PatientAppointment.objects.create(patient=patient, doctor=doctor, status='R')
            messages.success(request, f'Doctor assigned to patient {patient.user.username}')
        
        except (ValueError, Patient.DoesNotExist, Doctor.DoesNotExist):
            # Handle the case where patient_id is not a valid number
             messages.error(request, f'Invalid patient ID {patient_id}')
                
        return redirect('hpsapp:receptionist_dashboard')
    
class PatientListView(View):
    def get(self, request):
        patients = Patient.objects.all()
        context = {
            'patients': patients,
        }
        return render(request, 'hpsapp/patient_list.html', context=context)
    
logger = logging.getLogger( __name__)
def assign_doctor_to_patient(request, patient_id):
    if request.method == 'POST':
        doctor_id = request.POST.get('doctor_id')
        patient = get_object_or_404(Patient, user_id=patient_id)
        doctor = get_object_or_404(Doctor, user_id=doctor_id)
        
        try:
            # Create or update patient's appointment
            patient_appointment, _ = PatientAppointment.objects.get_or_create(patient=patient)
            patient_appointment.doctor = doctor
            patient_appointment.status = 'P'  # Update the status to 'Pre-consultated - In consultation'
            patient_appointment.save()

            messages.success(request, f"Doctor '{doctor.user.username}' assigned to patient '{patient.user.username}' successfully.")
        except Exception as e:
            # Log the error
            logger.exception("Error occurred while assigning a doctor to a patient:")
            
            # Display error message to the user
            messages.error(request, "An error occurred while assigning a doctor to the patient. Please try again later.")
        
    return redirect('hpsapp:patient_list')


# def assign_doctor_to_patient(request, patient_id):
#     if request.method == 'POST':
#         doctor_id = request.POST.get('doctor_id')
#         patient = get_object_or_404(Patient, user_id=patient_id)
#         doctor = get_object_or_404(Doctor, user_id=doctor_id)
#         # patient.doctor = doctor

#         try:
#             # Create or update patient's appointment
#             patient_appointment, _ = PatientAppointment.objects.get_or_create(patient=patient)
#             patient_appointment.doctor = doctor
#             patient_appointment.status = 'P'  # Update the status to 'Pre-consultated - In consultation'
#             patient_appointment.save()
#             print(patient_appointment.status, patient_appointment.doctor, patient_appointment.patient)
#             return redirect('hpsapp:receptionist_dashboard')
#         except Exception as e:
#             # Log the error            

templates/hpsapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HPS</title>
</head>
<body>
    {% block content %}
    {% endblock content %}
    
    {% block auth %}
        {% if user.is_authenticated %}
            <form action="{% url 'hpsapp:logout' %}" method="post">
                {% csrf_token %}
                
                <button type="submit">Logout</button>
            </form>
        {% endif %}
    {% endblock auth %}

</body>
</html>

templates/hpsapp/doctor_dashboard.html
{% extends 'hpsapp/base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>Home page content goes here.</p>
{% endblock content %}

templates/hpsapp/labtech_dashboard.html
{% extends 'hpsapp/base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>Home page content goes here.</p>
{% endblock content %}

templates/hpsapp/login.html
{% extends 'hpsapp/base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Log in</button>
  </form>

  <div>
    <p>Don't have an account?</p>
    <a href="{% url 'hpsapp:labtechnician_signup' %}">LabTech Signup</a>
    <a href="{% url 'hpsapp:doctor_signup' %}">Doctor's Signup</a>
  </div>
{% endblock %}

templates/hpsapp/nurse_dashboard.html
{% extends 'hpsapp/base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>Home page content goes here.</p>
{% endblock content %}

templates/hpsapp/patient_list.html
<!-- patient_list.html -->
{% extends 'hpsapp/base.html' %}

{% block content %}
    <h1>List of Patients</h1>
    {% if patients %}
        <table>
            <thead>
                <tr>
                    <th>Username</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Assign Doctor</th>
                    <!-- Add more columns as needed -->
                </tr>
            </thead>
            <tbody>
                {% for patient in patients %}
                    <tr>
                        <td>{{ patient.user.username }}</td>
                        <td>{{ patient.user.first_name }}</td>
                        <td>{{ patient.user.last_name }}</td>
                    
                        <td>
                            <form method="post" action="{% url 'hpsapp:assign_doctor_test' patient_id=patient.user.id %}">
                                {% csrf_token %}
                                <select name="doctor_id">
                                    {% for doctor in doctors %}
                                        <option value="{{ doctor.user.id }}">{{ doctor.user.username }}</option>
                                    {% endfor %}
                                </select>
                                <button type="submit">Assign Doctor</button>
                            </form>
                        </td>
                        <!-- Add more columns as needed -->
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No patients found.</p>
    {% endif %}
{% endblock %}

templates/hpsapp/receptionist_dashboard.html
{% extends 'hpsapp/base.html' %}

{% block content %}
    <h1>{{ title }}</h1>
    <p>Home page content goes here.</p>


    <section id="hero" class="d-flex align-items-top">
    <div class="container text-top position-relative" data-aos="fade-in" data-aos-delay="200">
        <!-- Message banner for search queries -->
        {% if messages %}
        <div class="alert-banner mt-0 text-center">
            {% for message in messages %}
            <div id="alert-{{ forloop.counter }}" class="alert alert-{{ message.tags }} alert-dismissible fade show"
                role="alert">
                {{ message }}
            </div>
            <script>
                setTimeout(function () {
                    $('#alert-{{ forloop.counter }}').fadeOut('slow');
                }, 8000);
            </script>
            {% endfor %}
        </div>
        {% endif %}
        <div class="search-content-container position-relative">
            <div class="search-content">
                <h1>Patient Search</h1>
                <div class="search-content-content">
                    <h2>Lorem ipsum dolor sit amet consectetur.</h2>
                </div>
            </div>
        </div>

        <form class="search-form" action="{% url 'hpsapp:receptionist_search' %}" method="get">
            <div class="form-group text-center">
                <div class="form-row">
                    <div class="col-md-6">
                        <input type="text" name="q" placeholder="Which patient are you looking for today?" class="form-control">
                    </div>

                </div>
                
                <div class="form-row">
                    <div class="col-md-12 text-center">
                        <input type="submit" value="Search" class="btn-get-started scrollto btn btn-success">
                    </div>
                </div>
            </div>
        </form>
        </div>
    </section>

    <section>
        <div>
            <p>Want to register a patient?</p>
            {% comment %} <a href="{% url 'hpsapp:register_patient' %}">Register Patient</a> {% endcomment %}
        </div>
    </section>

{% endblock content %}

templates/hpsapp/receptionist_patient_list.html
{% extends 'hpsapp/base.html' %}
{% load static %}

<!-- receptionist_patient_list.html -->
{% block content %}
  <h1>Search Results</h1>

<form method="post" action="{% url 'hpsapp:assign_doctor' patient_id=patient.user_id %}">
{% csrf_token %}
    {% if patients %}

    <table>
        <thead>
            <tr>
            <th>Patient</th>
            <th>Assign Doctor</th>
            <th>Action</th>
            </tr>
        </thead>
        
        <tbody>
            {% for patient in patients %}
            <tr>
                <td>{{ patient.user.username }}</td>
                <td>
                    <select name="doctor_id">
                        {% for doctor in doctors %}
                            <option value="{{ doctor.id }}">{{ doctor.user.username }}</option>
                        {% endfor %}
                    </select>
                    <input type="hidden" name="patient_id" value="{{ patient.id }}">
                </td>
                <td><button type="submit">Assign</button></td>   
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else%}
        <p>No results found</p>
    {% endif %}
</form>
{% endblock %}

templates/hpsapp/receptionist_register_patient.html
{% extends 'hpsapp/base.html' %}
{% load static %}


{% block content %}
<h1>{{ title }}</h1>

{% endblock content %}

templates/hpsapp/signup.html
{% extends 'hpsapp/base.html' %}

{% block content %}
  	<h2>{{ title }}</h2>
	
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Register</button>
	</form>

	<a href="{% url 'hpsapp:login' %}">Login</a>
{% endblock content %}